# Generated by Django 3.2 on 2022-03-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSourceLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=400, null=True)),
                ('imagelinks', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'ImageSourceLinks',
                'verbose_name_plural': 'ImageSourceLinks',
            },
        ),
    ]
