# Generated by Django 3.2 on 2022-03-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerecovery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tire_name', models.CharField(max_length=2000)),
                ('tire_price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Tire',
                'verbose_name_plural': 'Tires',
            },
        ),
    ]
