# Generated by Django 3.2 on 2022-03-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerecovery', '0003_tire_tiredescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='tirebrand',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
