# Generated by Django 3.2 on 2022-04-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerecovery', '0004_tire_tirebrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='tiresku',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
