# Generated by Django 3.2 on 2022-06-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerecovery', '0007_themecategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themecategories',
            name='category_url',
            field=models.TextField(blank=True, max_length=20000, null=True, unique=True),
        ),
    ]
