# Generated by Django 3.2 on 2022-06-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerecovery', '0008_alter_themecategories_category_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_url', models.TextField(blank=True, max_length=20000, null=True, unique=True)),
                ('crawled', models.BooleanField(default=False)),
            ],
        ),
    ]
