# Generated by Django 3.2 on 2022-06-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerecovery', '0009_agecategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=20000, null=True)),
                ('product_price', models.CharField(blank=True, max_length=20000, null=True)),
                ('product_age', models.CharField(blank=True, max_length=20000, null=True)),
                ('product_pieces', models.CharField(blank=True, max_length=20000, null=True)),
                ('items_number', models.CharField(blank=True, max_length=20000, null=True)),
                ('image_list', models.TextField(blank=True, max_length=20000, null=True)),
                ('Vip_points', models.TextField(blank=True, max_length=20000, null=True)),
                ('product_description', models.TextField(blank=True, max_length=20000, null=True)),
            ],
            options={
                'verbose_name': 'Lego',
                'verbose_name_plural': 'Legos',
            },
        ),
    ]
