# Generated by Django 3.2 on 2022-06-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerecovery', '0010_replogo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replogo',
            options={'verbose_name': 'RepLogo', 'verbose_name_plural': 'RepLogos'},
        ),
        migrations.AddField(
            model_name='replogo',
            name='product_features',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
