# Generated by Django 3.2 on 2022-06-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagerecovery', '0011_auto_20220617_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RepLogo',
            new_name='LogoToys',
        ),
    ]
