# Generated by Django 3.2 on 2022-06-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerecovery', '0012_rename_replogo_logotoys'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProductLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_url', models.TextField(blank=True, max_length=20000, null=True, unique=True)),
                ('crawled', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='logotoys',
            options={'verbose_name': 'LogoToys', 'verbose_name_plural': 'LogoToys'},
        ),
    ]
