# Generated by Django 3.2 on 2022-06-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerecovery', '0013_auto_20220625_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasbroToys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, max_length=20000, null=True)),
                ('product_name', models.CharField(blank=True, max_length=20000, null=True)),
                ('age', models.CharField(blank=True, max_length=20000, null=True)),
                ('category_url', models.CharField(blank=True, max_length=20000, null=True)),
                ('product_description', models.CharField(blank=True, max_length=20000, null=True)),
                ('image_list', models.TextField(blank=True, max_length=20000, null=True)),
            ],
            options={
                'verbose_name': 'HasbroToys',
                'verbose_name_plural': 'HasbroToys',
            },
        ),
    ]
